# Generated by Django 4.2.3 on 2023-07-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите имя заказчика', max_length=35, verbose_name='Имя закзчика')),
                ('last_name', models.CharField(help_text='Введите фамилию заказчика', max_length=35, null=True, verbose_name='Фамилия заказчика')),
                ('phone', models.CharField(help_text='Ведите номер телефона закзчика', max_length=15, null=True, verbose_name='Номер телефона заказчика')),
                ('tg_un', models.URLField(help_text='Ведите username закзчика', max_length=50, null=True, verbose_name='Username заказчика')),
                ('notes', models.TextField(help_text='Заметки заказчика', null=True, verbose_name='Заметки заказчика')),
            ],
        ),
    ]
